*** Makefile.orig	2020-11-03 14:54:30.710541828 +0000
--- Makefile	2020-11-03 14:57:04.274541736 +0000
*************** CONFIG_RTW_SDIO_PM_KEEP_POWER = y
*** 113,120 ****
  CONFIG_MP_VHT_HW_TX_MODE = n
  ###################### Platform Related #######################
  CONFIG_PLATFORM_ARM_NV_NANO = n 
! CONFIG_PLATFORM_I386_PC = y
  CONFIG_PLATFORM_ARM_RPI = n
  CONFIG_PLATFORM_ANDROID_X86 = n
  CONFIG_PLATFORM_ANDROID_INTEL_X86 = n
  CONFIG_PLATFORM_JB_X86 = n
--- 113,121 ----
  CONFIG_MP_VHT_HW_TX_MODE = n
  ###################### Platform Related #######################
  CONFIG_PLATFORM_ARM_NV_NANO = n 
! CONFIG_PLATFORM_I386_PC = n
  CONFIG_PLATFORM_ARM_RPI = n
+ CONFIG_PLATFORM_ARM64_RPI = y
  CONFIG_PLATFORM_ANDROID_X86 = n
  CONFIG_PLATFORM_ANDROID_INTEL_X86 = n
  CONFIG_PLATFORM_JB_X86 = n
*************** ARCH := arm
*** 1247,1252 ****
--- 1248,1266 ----
  KVER := $(shell uname -r)
  KSRC := /lib/modules/$(KVER)/build
  MODDESTDIR := /lib/modules/$(KVER)/kernel/drivers/net/wireless/
+ INSTALL_PREFIX :=
+ STAGINGMODDIR := /lib/modules/$(KVER)/kernel/drivers/staging
+ endif
+ 
+ ifeq ($(CONFIG_PLATFORM_ARM64_RPI), y)
+ EXTRA_CFLAGS += -DCONFIG_LITTLE_ENDIAN
+ EXTRA_CFLAGS += -DCONFIG_IOCTL_CFG80211 -DRTW_USE_CFG80211_STA_EVENT
+ EXTRA_CFLAGS += -Wno-bool-operation
+ EXTRA_CFLAGS += -fno-stack-protector
+ ARCH := arm64
+ KVER := $(shell uname -r)
+ KSRC := /lib/modules/$(KVER)/build
+ MODDESTDIR := /lib/modules/$(KVER)/kernel/drivers/net/wireless/
  INSTALL_PREFIX :=
  STAGINGMODDIR := /lib/modules/$(KVER)/kernel/drivers/staging
  endif
